<?php

namespace App\Models;

use App\Traits\IconTrait;

/**
 * App\Models\InvoiceItemImage
 *
 * Eloquent model representing an image attached to an invoice item.
 *
 * @property int $id                           // Primary key (auto-increment ID)
 * @property int $invoice_item_id              // Foreign key referencing the invoice item
 * @property string $filename                  // Original filename of the uploaded image
 * @property string|null $hashname             // Stored filename (hashed for uniqueness)
 * @property string|null $image                // Optional image field (could be path/reference)
 * @property string|null $size                 // File size (e.g., KB/MB)
 * @property string|null $external_link        // Optional external file link instead of local
 * @property \Illuminate\Support\Carbon|null $created_at // Timestamp when record created
 * @property \Illuminate\Support\Carbon|null $updated_at // Timestamp when record updated
 * 
 * Accessors & Attributes
 * @property-read mixed $file_url              // Dynamically generated file URL (local or external)
 * @property-read mixed $icon                  // Icon associated with file type (via IconTrait)
 * @property-read mixed $file                  // Relative file path or external link
 *
 * Eloquent helper methods for querying (auto-generated by Laravel)
 * @method static \Illuminate\Database\Eloquent\Builder|InvoiceItemImage newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|InvoiceItemImage newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|InvoiceItemImage query()
 * @method static \Illuminate\Database\Eloquent\Builder|InvoiceItemImage whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|InvoiceItemImage whereExternalLink($value)
 * @method static \Illuminate\Database\Eloquent\Builder|InvoiceItemImage whereFilename($value)
 * @method static \Illuminate\Database\Eloquent\Builder|InvoiceItemImage whereHashname($value)
 * @method static \Illuminate\Database\Eloquent\Builder|InvoiceItemImage whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|InvoiceItemImage whereInvoiceItemId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|InvoiceItemImage whereSize($value)
 * @method static \Illuminate\Database\Eloquent\Builder|InvoiceItemImage whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class InvoiceItemImage extends BaseModel
{
    use IconTrait; // Adds methods/properties for handling icons

    // Base directory where invoice item files are stored
    const FILE_PATH = 'invoice-files';

    // Attributes automatically appended when model is serialized
    protected $appends = ['file_url', 'icon', 'file'];

    // Mass-assignable fields
    protected $fillable = ['invoice_item_id', 'filename', 'hashname', 'size', 'external_link'];

    /**
     * Accessor: Returns the full file URL.
     * If external_link is provided, use it (check if it's a proper URL or local path).
     * Otherwise, generate the local S3 path with invoice item ID + hashname.
     */
    public function getFileUrlAttribute()
    {
        if ($this->external_link) {
            return str($this->external_link)->contains('http')
                ? $this->external_link
                : asset_url_local_s3($this->external_link);
        }

        return asset_url_local_s3(InvoiceItemImage::FILE_PATH . '/' . $this->invoice_item_id . '/' . $this->hashname);
    }

    /**
     * Accessor: Returns either external link OR relative local file path.
     */
    public function getFileAttribute()
    {
        return $this->external_link
            ?: (InvoiceItemImage::FILE_PATH . '/' . $this->invoice_item_id . '/' . $this->hashname);
    }
}
