<?php

namespace App\Models;

use App\Traits\HasCompany;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * App\Models\ProductCategory
 *
 * (Docblock generated by Laravel IDE Helper – left unchanged)
 */
class ProductCategory extends BaseModel
{
    use HasCompany; // Trait to automatically scope/handle company-related records

    // Explicit database table name
    protected $table = 'product_category';

    /**
     * Relationship: A category can have many subcategories.
     */
    public function subCategories(): HasMany
    {
        return $this->hasMany(ProductSubCategory::class, 'category_id');
    }
}
