<?php

namespace App\Models;

use App\Traits\HasCompany;
use App\Traits\CustomFieldsTrait;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Modules\Purchase\Entities\PurchaseStockAdjustment;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

/**
 * App\Models\Product
 *
 * (Docblock generated by Laravel IDE Helper – left untouched)
 */
class Product extends BaseModel
{
    use HasCompany;
    use HasFactory, CustomFieldsTrait;

    protected $table = 'products'; // Explicit DB table name
    const FILE_PATH = 'products';  // Path for storing product files (images/downloads)

    protected $fillable = ['name', 'price', 'description', 'taxes'];

    // These attributes will always be appended to model JSON output
    protected $appends = ['total_amount', 'image_url', 'download_file_url', 'image'];

    // Always eager-load the tax relationship
    protected $with = ['tax'];

    const CUSTOM_FIELD_MODEL = 'App\Models\Product';

    /**
     * Return product image URL (from default_image).
     * - In dev/demo environment: return as-is if it's already a full http link.
     * - Otherwise: return from local S3 asset helper.
     */
    public function getImageUrlAttribute()
    {
        if (app()->environment(['development','demo']) && str_contains($this->default_image, 'http')) {
            return $this->default_image;
        }

        return ($this->default_image)
            ? asset_url_local_s3(Product::FILE_PATH . '/' . $this->default_image)
            : '';
    }

    /**
     * Return the image path or full URL depending on storage.
     */
    public function getImageAttribute()
    {
        if ($this->default_image) {
            return str($this->default_image)->contains('http')
                ? $this->default_image
                : (Product::FILE_PATH . '/' . $this->default_image);
        }

        return $this->default_image;
    }

    /**
     * Get downloadable file URL if product is marked as downloadable.
     */
    public function getDownloadFileUrlAttribute()
    {
        return ($this->downloadable_file)
            ? asset_url_local_s3(Product::FILE_PATH . '/' . $this->downloadable_file)
            : null;
    }

    /**
     * Relationship: belongs to a tax (even if soft-deleted).
     */
    public function tax(): BelongsTo
    {
        return $this->belongsTo(Tax::class)->withTrashed();
    }

    /**
     * Relationship: product is linked with many deals/leads.
     */
    public function leads(): BelongsToMany
    {
        return $this->belongsToMany(Deal::class, 'lead_products');
    }

    /**
     * Helper: fetch a tax by its ID (including trashed).
     */
    public static function taxbyid($id)
    {
        return Tax::where('id', $id)->withTrashed();
    }

    /**
     * Relationship: product belongs to a category.
     */
    public function category(): BelongsTo
    {
        return $this->belongsTo(ProductCategory::class, 'category_id');
    }

    /**
     * Relationship: product belongs to a unit type.
     */
    public function unit(): BelongsTo
    {
        return $this->belongsTo(UnitType::class, 'unit_id');
    }

    /**
     * Relationship: product belongs to a subcategory.
     */
    public function subCategory(): BelongsTo
    {
        return $this->belongsTo(ProductSubCategory::class, 'sub_category_id');
    }

    /**
     * Calculate product total amount = price + tax.
     */
    public function getTotalAmountAttribute()
    {
        if (!is_null($this->price) && !is_null($this->tax)) {
            return (int)$this->price + ((int)$this->price * ((int)$this->tax->rate_percent / 100));
        }

        return '';
    }

    /**
     * Relationship: files linked to product (images, docs, etc.).
     */
    public function files(): HasMany
    {
        return $this->hasMany(ProductFiles::class, 'product_id')->orderByDesc('id');
    }

    /**
     * Get tax list as formatted string: "TaxName: Rate%, ..."
     */
    public function getTaxListAttribute()
    {
        $productItem = Product::findOrFail($this->id);
        $taxes = '';

        if ($productItem && $productItem->taxes) {
            $numItems = count(json_decode($productItem->taxes));

            if (!is_null($productItem->taxes)) {
                foreach (json_decode($productItem->taxes) as $index => $tax) {
                    $tax = $this->taxbyid($tax)->first();
                    $taxes .= $tax->tax_name . ': ' . $tax->rate_percent . '%';

                    $taxes = ($index + 1 != $numItems) ? $taxes . ', ' : $taxes;
                }
            }
        }

        return $taxes;
    }

    /**
     * Relationship: order items associated with this product.
     */
    public function orderItem(): HasMany
    {
        return $this->hasMany(OrderItems::class, 'product_id');
    }

    /**
     * Relationship: inventory adjustments for this product.
     */
    public function inventory()
    {
        /** @phpstan-ignore-next-line */
        return $this->hasMany(PurchaseStockAdjustment::class, 'product_id');
    }
}
